### ISSUE TITLE
Too many open issues and requests!

### ISSUE THREAD

**Issue by domalex** [keyboardio/Chrysalis#1359] opened 2024-11-11 10:15 UTC
I have decided to contribute on Kickstarter to your Preonic keyboard campaign. As Chrysalis is used to program all of your keyboards I am deeply concerned that nobody seems to seriously following up on issues and requests reported by your customers. As of today (11.11.2024) there are 147 issues and 4 pull requests open, waiting to be solved! This situation requires serious improvement! The best keyboard isn't any good if the software to program it with isn't being developed timely.

**Comment by obra** [comment] 2024-11-11 17:39
This is a duplicate of the comment you posted on the preonic kickstarter. I'll reply to you there, likely later today.

**Closed by obra** 2024-11-11 17:39 UTC
Labels: bug

**Comment by domalex** [comment] 2024-11-12 11:00
I posted it twice because the thread seems relevant for preonic campaign contributors as well as for current and future Chrysalis users.
