### ISSUE TITLE
Error when Crysalis is trying to update

### ISSUE THREAD

**Issue by Random-Man81** [keyboardio/Chrysalis#1269] opened 2023-05-12 21:53 UTC
[chrysalis-debug.json.txt](https://github.com/keyboardio/Chrysalis/files/11467988/chrysalis-debug.json.txt)
![Screenshot 2023-05-12 175208](https://github.com/keyboardio/Chrysalis/assets/94929286/c0077762-3a9e-4c88-95ca-236033f5c4e3)
Error about checksum mismatch when trying to update to 0.13.2

**Comment by thunderkeys** [comment] 2023-05-21 14:09
I get the same error (same hashes as well).

**Comment by necsoiu** [comment] 2023-05-21 15:57
I have the same problem.

**Comment by TrueFalcon** [comment] 2023-05-22 10:28
I gave up on 13.# and went back to 12.0. It works fine. Awaiting next higher version...

**Comment by obra** [comment] 2023-07-31 20:35
I've finally tracked this one down to a race condition caused by the "master" build overwriting the release build of the exact same version at publication time. I've manually repaired the build information, but we're now running into an Authenticode signature issue. Coupled with the fact that our old certificate expired yesterday and new certificates are only being issued in a way that makes github-based builds...more complicated and expensive, I'm not yet sure how we're going to sort this out.

**Comment by obra** [comment] 2024-02-26 21:05
Chrysalis now runs in-browser using WebSerial and WebUSB and this functionality has been rewritten, so I'm closing out this issue as obsolete. Please don't hesitate to open a new issue if https://chrysalis.keyboard.io exhibits the same behavior

**Closed by obra** 2024-02-26 21:05 UTC
