### ISSUE TITLE
You can no longer get to the preferences page without having connected to a keyboard.

### ISSUE THREAD

**Issue by obra** [keyboardio/Chrysalis#463] opened 2020-02-14 20:05 UTC

**Comment by algernon** [comment] 2020-02-14 20:52
Oh, shoot. I accidentally removed that part when rebasing.

**Comment by algernon** [comment] 2020-02-18 19:38
Hmm... interesting, I can't reproduce?

![Screenshot from 2020-02-18 20-32-58](https://user-images.githubusercontent.com/17243/74771405-6154c300-528e-11ea-9ffd-51a317778e55.png)

![Screenshot from 2020-02-18 20-33-04](https://user-images.githubusercontent.com/17243/74771392-5c900f00-528e-11ea-8ede-f4399e23f8c7.png)

I can get to preferences even if I start up Chrysalis, and never connect to a keyboard, not just when I connect & disconnect.

**Comment by algernon** [comment] 2020-04-29 17:57
@obra Is this still a problem?

**Comment by pm0u** [comment] 2020-05-02 17:09
I can confirm I can also get to the preferences screen on a clean startup with no keyboard connected in the latest master

**Comment by algernon** [comment] 2020-05-02 18:30
@pm0u Thanks for testing!

Closing this then.

**Closed by algernon** 2020-05-02 18:30 UTC
Labels: bug
