### ISSUE TITLE
Numpad area keys no longer color map

### ISSUE THREAD

**Issue by HeavyThumper** [keyboardio/Chrysalis#1246] opened 2022-12-27 20:47 UTC
I don't know exactly when it happened but now the keys for the numpad area no longer respond to any color changes - at least for layer 0. They do seem to still change for layer 2.

So for example, the top row of number keys by default I want to have orange. At the moment #6 and #0 are orange, while 7-9 are red which matches the rest of the letter keys. Toggling numlock,  which I have defined as locking to layer 1, changes colors outside of the numpad area per layer 1 definition. Using the palm keys, which shift to layer 2, does change most of the right keyboard unit (shades of blue) as defined except for the num key.

Num key now is a pulsing/fading blue irregardless of layer or programming. If I rapidly press the palm keys and time it right I can see the num key momentarily light a different color (not the one I have defined for layer 1) before it resumes its pulsing.

**Comment by obra** [comment] 2024-11-11 17:47
This is a dupe of #430

**Closed by obra** 2024-11-11 17:47 UTC
Labels: bug
