### ISSUE TITLE
Blank screen after pasting layout and switching layer

### ISSUE THREAD

**Issue by fluffy-critter** [keyboardio/Chrysalis#363] opened 2019-03-21 20:47 UTC
**Describe the bug**

Get a blank window after pasting a JSON layout from the clipboard

**To Reproduce**

1. go to layer 0, select copy/paste 
2. paste from clipboard
3. press 'okay'
4. go to layer 1

**Expected behavior**

Expected to be able to then edit layer 1

**Screenshots**

[localhost-1553201025958.log](https://github.com/keyboardio/Chrysalis/files/2993912/localhost-1553201025958.log)

**Desktop (please complete the following information):**
 - OS: macOS
 - Chrysalis Version: 9cb6de1

**Additional context**

**Comment by mattvenn** [comment] 2019-05-14 15:53
confirmed. Also I see this with copying to clipboard as well.

**Comment by obra** [comment] 2019-07-17 16:10
This should not have been resolved if the patch was applied to Dygma's fork, but not the core.

**Comment by 0957758592** [comment] 2019-08-04 11:26
It looks like this issue should be closed, cause were being merged.

**Comment by fluffy-critter** [comment] 2019-08-04 12:38
As a note, if you put text like "Fixes #363" into the PR comment, then the issue will automatically close when the merge happens.

**Comment by 0957758592** [comment] 2019-08-04 12:40
@fluffy-critter 
Thank you!

**Closed** 2019-08-19 17:53 UTC
Labels: bug
